### ISSUE TITLE
python 2.7 compatible version

### ISSUE THREAD

**Issue by ashwinprasadme** [iot-salzburg/STL-tweaker#1]
can we have a branch with python 2.7 compatible code?

**Comment by ChristophSchranz** [comment]
At the moment I'm working on optimizing performance and 3mf handling, but when finished I hope I'll find some time to do that. However, you may have to be patient for a month. If anyone should translate it sooner, please send me a copy to share it on github.

**Comment by ChristophSchranz** [comment]
The Tweaker master-branch is now also compatible for python version 2.7.

If you have any issues, please let me know.

**Comment by ashwinprasadme** [comment]
Awesome thanks, i had integrated this with cura and its working sweet

**Comment by ChristophSchranz** [comment]
Super, can you send us the cura modifications or branch it?
I really want to see the an auto-rotate function in cura ;)
